### ISSUE TITLE
安装中文输入法 时的命令 错误

### ISSUE THREAD

**Issue by sialvsic** [thoughtworks-academy/everyone-can-be-geek-style#2]
$ sudo apt update
$ sudo apt install ibus-libpinyin

-> 应该为
$ sudo apt-get update
$ sudo apt-get install ibus-libpinyin

**Comment by leozhang2018** [comment]
视系统版本而定，Ubuntu 16.04 一个新增 feature 而已。
apt 并不是一个新命令，它与 apt-get 命令也没有本质上的区别，而且已经在 Debian 中使用了多年，语法与apt-get 非常相似，而且简捷。
