### ISSUE TITLE
Terminal shows an error when install Skype

### ISSUE THREAD

**Issue by Poseiden** [thoughtworks-academy/everyone-can-be-geek-style#3]
Sorry , my OS is Ubuntu14.04 (not 16 like your guide said)

But l don't think there are some large differences between two . (If there are ,then sorry about these words)

Anyway , there is my solution by ubuntu community.(l just hope it can help some other students who meets same error in terminal ) 

Users of 64-bit Ubuntu, should enable MultiArch if it isn't already enabled by running the command

sudo dpkg --add-architecture i386

Since Ubuntu 10.04 (Lucid Lynx), Skype is part of the Canonical partner repository. To install Skype add the Canonical Partner Repository. You can do this by running the command

sudo add-apt-repository "deb http://archive.canonical.com/ $(lsb_release -sc) partner"

Then install Skype via the Software-Center or via the Terminal.

sudo apt-get update && sudo apt-get install skype

quoted from :

https://help.ubuntu.com/community/Skype

another help by skype official : 

https://community.skype.com/t5/Linux/Ubuntu-14-04-LTS-64-bit-amp-Skype/td-p/3684533

Thanks .

**Comment by sialvsic** [comment]
@bbos1994 you could directly visit skype official website https://www.skype.com/en/ download and install it

**Comment by Poseiden** [comment]
Sorry , l don't see  skype of Ubuntu version in official website  like you said . Did l miss anything please ?

**Comment by sialvsic** [comment]
@bbos1994  https://www.skype.com/en/download-skype/skype-for-computer/   in this page. you could choose you linux distribution  and i see ubuntu version of 12.04 and 10.04 but there has not a 14.04 version .  I don't know if you could install a 12.04 version in you 14.04 version .  you could hava a try .

P.S:  May be the skype official check you system version and  prohibition visit

**Comment by Poseiden** [comment]
@sialvsic Thank you but  the nearest build is for Ubuntu12 (not even sure it is for 32 bit or 64bit ) in that dropdown list , and l don't know whether it works on Ubuntu14(64 bit).
If someone looks for  help on installing skype in Ubuntu14 , which l quoted (https://help.ubuntu.com/community/Skype or https://community.skype.com/t5/Linux/Ubuntu-14-04-LTS-64-bit-amp-Skype/td-p/3684533 )  will be referenced . Because  l had installed skype successfully before l opened this issue . Thank you . (⊙o⊙)
